/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'background': '#10131a',
        'surface': '#10131a',
        'surface-container-lowest': '#0b0e15',
        'surface-container-low': '#191b23',
        'surface-container': '#1d1f27',
        'surface-container-high': '#272a32',
        'surface-container-highest': '#32353d',
        'surface-glass-border': '#1e293b',
        'on-surface': '#e1e2ec',
        'on-surface-variant': '#c7c4d7',
        'outline': '#908fa0',
        'outline-variant': '#464554',
        'primary': '#c0c1ff',
        'on-primary': '#1000a9',
        'primary-container': '#8083ff',
        'secondary': '#4cd7f6',
        'secondary-container': '#03b5d3',
        'on-secondary': '#003640',
        'on-secondary-fixed': '#001f26',
        'tertiary': '#4edea3',
        'tertiary-fixed': '#6ffbbe',
        'on-tertiary': '#003824',
        'code-amber': '#f59e0b',
      },
      fontFamily: {
        display: ['"Space Grotesk"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        mono: ['"Space Mono"', 'monospace'],
      },
      fontSize: {
        'display': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'display-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'title-md': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px' }],
        'body-md': ['15px', { lineHeight: '24px' }],
        'body-sm': ['13px', { lineHeight: '20px' }],
        'label-md': ['13px', { lineHeight: '18px', letterSpacing: '0.04em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.06em', fontWeight: '500' }],
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        'gutter': '1.5rem',
      },
      maxWidth: {
        'site': '1280px',
      },
    },
  },
  plugins: [],
}
